apiVersion: apps/v1
kind: Deployment
metadata:
  annotations: {}
  labels:
    app: etymo-apiservice
  name: etymo-apiservice
spec:
  minReadySeconds: 60
  replicas: 1
  selector:
    matchLabels:
      app: etymo-apiservice
  strategy:
    type: Recreate
  template:
    metadata:
      annotations: {}
      labels:
        app: etymo-apiservice
    spec:
      containers:
      - args: []
        envFrom:
        - configMapRef:
            name: etymo-apiservice
        image: '{{ .Values.images.etymoapiservice }}'
        env:
          - name: existingPostgres
            valueFrom:
              secretKeyRef:
               name: {{ .Values.secrets.connectionStrings.existingPostgres.name | quote}} 
               key: {{ .Values.secrets.connectionStrings.existingPostgres).key | quote }}
        imagePullPolicy: IfNotPresent
        name: etymo-apiservice
        ports:
        - containerPort: 8080
          name: http
        - containerPort: 8443
          name: https
      terminationGracePeriodSeconds: 180