apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: dataprotection-keys-pvc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Mi
  storageClassName: openebs-hostpath