{{- if .Values.apiservice.tls.enabled }}
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ .Release.Name }}-apiservice-tls
spec:
  secretName: {{ .Values.apiservice.tls.secretName }}
  issuerRef:
    name: {{ .Values.apiservice.tls.issuer }}
    kind: ClusterIssuer
  commonName: {{ .Release.Name }}-apiservice.{{ .Release.Namespace }}.svc.cluster.local
  dnsNames:
    - {{ .Release.Name }}-apiservice
    - {{ .Release.Name }}-apiservice.{{ .Release.Namespace }}
    - {{ .Release.Name }}-apiservice.{{ .Release.Namespace }}.svc
    - {{ .Release.Name }}-apiservice.{{ .Release.Namespace }}.svc.cluster.local
  usages:
    - server auth
{{- end }}