apiVersion: apps/v1
kind: Deployment
metadata:
  annotations: {}
  labels:
    app: etymo-webfrontend
  name: etymo-webfrontend
spec:
  minReadySeconds: 60
  replicas: 1
  selector:
    matchLabels:
      app: etymo-webfrontend
  strategy:
    type: Recreate
  template:
    metadata:
      annotations: {}
      labels:
        app: etymo-webfrontend
    spec:
      containers:
      - args: []
        envFrom:
        - configMapRef:
            name: etymo-webfrontend
        image: '{{ .Values.images.etymowebfrontend }}'
        env:
          - name: existingPostgres
            valueFrom:
              secretKeyRef:
               name: {{ (split "/" .Values.secrets.connectionStrings.existingPostgres).0 }} 
               key: {{ (split "/" .Values.secrets.connectionStrings.existingPostgres).1 }}
        imagePullPolicy: IfNotPresent
        name: etymo-webfrontend
        ports:
        - containerPort: 8080
          name: http
        - containerPort: 8443
          name: https
      terminationGracePeriodSeconds: 180