apiVersion: v1
kind: Service
metadata:
  annotations: {}
  labels:
    app: keycloak
  name: keycloak
spec:
  ports:
  - name: http
    port: 8080
    targetPort: 0
  selector:
    app: keycloak
  type: ClusterIP