on:
  workflow_dispatch:
  push:
    # Run when commits are pushed to mainline branch (main or master)
    # Set this to the mainline branch you are using
    branches:
      - main

permissions:
  id-token: write
  contents: write
  packages: write
  pull-requests: write

jobs:
  build:
    if: github.ref == 'refs/heads/main' && github.event_name != 'pull_request' && "! contains(github.event.head_commit.message, 'Merge pull request')"
    runs-on: ubuntu-latest
    defaults: 
      run: 
        working-directory: ./${{ github.event.repository.name }}.AppHost
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          source-url: https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json
          dotnet-version: 8.0.x
        env: 
          NUGET_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}

      - name: Install GitVersion
        uses: gittools/actions/gitversion/setup@v3.0.0
        with:
          versionSpec: '6.x'

      - name: Determine Version
        id: version-git
        uses: gittools/actions/gitversion/execute@v0

      - name: Create a new branch
        run: git checkout -b build-release-${{ env.GitVersion_SemVer }}

      - name: Install .NET Aspire workload
        run: dotnet workload install aspire

      - name: Aspir8 Install
        run: dotnet tool install -g aspirate --prerelease

      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --no-restore --configuration Release

      - name: Test
        run: dotnet test --configuration release --logger trx /p:CollectCoverage=true /p:CoverletOutputFormat=opencover

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Aspire Init
        run: aspirate init --non-interactive --container-registry ghcr.io --container-repository-prefix ${{ github.repository }} --container-image-tag ${{ env.GitVersion_SemVer }} --disable-secrets 

      - name: Aspire Generate Helm Chart
        run: aspirate generate --non-interactive --output-format helm --disable-secrets --include-dashboard true --image-pull-policy IfNotPresent

      - name: Add, Commit, Push to Github
        run: |
            git config --global user.name '${{ github.actor }}'
            git config --global user.email '${{ github.actor }}@users.noreply.github.com'
            git add ./aspirate-output
            git commit -m "Release v${{ env.GitVersion_SemVer }} images"
            git push --set-upstream origin build-release-${{ env.GitVersion_SemVer }}

      - name: create pull request
        run: gh pr create -B main -H build-release-${{ env.GitVersion_SemVer }} --title 'Merge build-release-${{ env.GitVersion_SemVer }} into main' --body 'Created by Github action'
        env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

