on:
  workflow_dispatch:
  push:
    # Run when commits are pushed to mainline branch (main or master)
    # Set this to the mainline branch you are using
    branches:
      - main
    paths:
      - "Etymo.AppHost/**"

permissions:
  id-token: write
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          source-url: https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json
          dotnet-version: 8.0.x
        env: 
          NUGET_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}

      - name: Install .NET Aspire workload
        run: dotnet workload install aspire

      - name: Aspir8 Install
        run: dotnet tool install -g aspirate --prerelease

      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --no-restore --configuration Release

      - name: Test
        run: dotnet test --configuration release --logger trx /p:CollectCoverage=true /p:CoverletOutputFormat=opencover

      - name: Docker Login to GitHub Container Registry
        if: github.event_name != 'pull_request'
        run:
          docker login ghcr.io -u ${{ github.repository_owner }} --password ${{ secrets.GITHUB_TOKEN }}

      - name: Aspire Init
        run: aspirate init --non-interactive --container-registry ghcr.io --container-repository-prefix ${{ github.event.repository.name }} --disable-secrets

      - name: Aspire Generate
        run: aspirate generate --non-interactive --output-format helm --disable-secrets --include-dashboard true --image-pull-policy IfNotPresent
