name: "Publish charts to repo"

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  publish:
    if: github.ref == 'refs/heads/main' && contains(github.event.head_commit.message, 'from ${{ github.actor }}/build-release')
    runs-on: ubuntu-latest
    permissions:
      pages: write
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Install Helm
        uses: azure/setup-helm@v4

      - name: Run chart-releaser
        uses: helm/chart-releaser-action@v1.6.0
        with:
          charts_dir: ${{ github.event.repository.name }}.AppHost/aspirate-output
        env:
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"