services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: etymo_test
    ports:
      - "5433:5432"
    volumes:
      - ./seed.sql:/docker-entrypoint-initdb.d/seed.sql  # Mount seed.sql to init directory
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5